project:
  type: website
  title: "The Crypto Business Solution / 链上商业解决方案"
  output-dir: docs

website:
  title: "The Crypto Business Solution"
  navbar:
    left:
      - text: "English"
        href: en/
      - text: "中文"
        href: zh/
  page-footer:
    center: |
      Copyright 2025 Global Business Chain, Inc.
      <br>
      <a href="en/">English</a> | <a href="zh/">中文</a>

format:
  html:
    theme: cosmo
    toc: true
    css: _resources/css/custom.css