project:
  type: website
  title: "The Crypto Business Solution / 鏈上商業解決方案"
  output-dir: docs

website:
  title: "The Crypto Business Solution"
  navbar:
    left:
      - text: "English"
        href: en/
      - text: "简体中文"
        href: zh/
      - text: "繁體中文"
        href: zh-tw/
  page-footer:
    center: |
      Copyright 2025 Global Business Chain, Inc.
      <br>
      <a href="en/">English</a> | <a href="zh/">简体中文</a> | <a href="zh-tw/">繁體中文</a>

format:
  html:
    theme: cosmo
    toc: true
    css: _resources/css/custom.css